export default {
	CHOREGRAPHY: 'CHOREGRAPHY',
	MOVES_TIMEOUTS: 'MOVES_TIMEOUTS',
	MOVE_SHOW: 'MOVE_SHOW',
	MOVE_HIDE: 'MOVE_HIDE',
	MOVE_DURATION: 3000,
	MOVE_TOLERANCE_OK: 200,
	MOVE_TOLERANCE_GOOD: 100,
	MOVE_TOLERANCE_EXCELLENT: 50,
};
