export default {
	GAME_IDLE: 'GAME_IDLE',
	GAME_INTRO: 'GAME_INTRO',
	GAME_TUTO: 'GAME_TUTO',
	GAME_WAIT: 'GAME_WAIT',
	GAME_LOAD: 'GAME_LOAD',
	GAME_PLAY: 'GAME_PLAY',
	GAME_SAVE: 'GAME_SAVE',
	GAME_RANK: 'GAME_RANK',
	GAME_END: 'GAME_END',
	GAME_INTRO_DURATION: 5000,
	GAME_WAIT_DURATION: 10000,
	GAME_LOAD_DURATION: 3000,
};
