export default {
	GAME_IDLE: 'GAME_IDLE',
	GAME_INTRO: 'GAME_INTRO',
	GAME_WAIT: 'GAME_WAIT',
	GAME_LOAD: 'GAME_LOAD',
	GAME_PLAY: 'GAME_PLAY',
	GAME_END: 'GAME_END',
	GAME_INTRO_DURATION: 'GAME_INTRO_DURATION',
	GAME_WAIT_DURATION: 'GAME_WAIT_DURATION',
	GAME_LOAD_DURATION: 'GAME_LOAD_DURATION',
	GAME_END_DELAY: 1000,
};
