export default {
	PAD: 'PAD',
	SCORE: 'SCORE',
	GAME: 'GAME',
	TARGET_STEP: 'TARGET_STEP',
	RESET_TARGET_STEPS: 'RESET_TARGET_STEPS',
	PLAYER_STEP: 'PLAYER_STEP',
	RESET_PLAYER_STEPS: 'RESET_PLAYER_STEPS',
	ADDITIONAL_TIME: 150
};
