export default {
	PAD: 'PAD',
	SCORE: 'SCORE',
	GAME: 'GAME',
	GAME_TIMEOUT: 'GAME_TIMEOUT',
	STEP: 'STEP',
	STEPS_RESET: 'STEPS_RESET',
	CHOREGRAPHY: 'CHOREGRAPHY',
	CHOREGRAPHY_RESET: 'CHOREGRAPHY_RESET',
	ARROWS_TIMEOUTS: 'ARROWS_TIMEOUTS',
	ARROW_ADD: 'ARROW_ADD',
	ARROW_REMOVE: 'ARROW_REMOVE',
	ARROW_STATUS: 'ARROW_STATUS',
	MOVE_RANGE_OK: 400,
	MOVE_RANGE_BIEN: 200,
	MOVE_RANGE_EXCELLENT: 100
};
