export default {
	PAD: 'PAD',
	SCORE: 'SCORE',
	GAME: 'GAME',
	GAME_TIMEOUT: 'GAME_TIMEOUT',
	STEP: 'STEP',
	STEPS_RESET: 'STEPS_RESET',
	CHOREGRAPHY: 'CHOREGRAPHY',
	MOVE_TIMEOUTS: 'MOVE_TIMEOUTS',
	MOVE_SHOW: 'MOVE_SHOW',
	MOVE_PLAY: 'MOVE_PLAY',
	MOVE_HIDE: 'MOVE_HIDE',
	MOVE_RANGE_OK: 400,
	MOVE_RANGE_BIEN: 200,
	MOVE_RANGE_EXCELLENT: 100
};
