export default {
	MOVES_TIMEOUTS: 'MOVES_TIMEOUTS',
	MOVE_SHOW: 'MOVE_SHOW',
	MOVE_HITTABLE: 'MOVE_HITTABLE',
	MOVE_HIDE: 'MOVE_HIDE',
	MOVE_UNHITTABLE: 'MOVE_UNHITTABLE',
	MOVE_DURATION: 8000,
	MOVE_TOLERANCE_OK: 200,
	MOVE_TOLERANCE_GOOD: 100,
	MOVE_TOLERANCE_EXCELLENT: 50,
};
