export default {
	MOVES_TIMEOUTS: 'MOVES_TIMEOUTS',
	MOVES_END_DELAY: 1000,
	MOVE_SHOW: 'MOVE_SHOW',
	MOVE_COMMENTABLE: 'MOVE_COMMENTABLE',
	MOVE_HIDE: 'MOVE_HIDE',
	MOVE_UNCOMMENTABLE: 'MOVE_UNCOMMENTABLE',
	MOVE_DURATION: 4000,
	MOVE_TOLERANCE_OK: 200,
	MOVE_TOLERANCE_GOOD: 100,
	MOVE_TOLERANCE_EXCELLENT: 50,
};
